Ensure domain models have dispatcher at flush, only in debug mode
swagindustries/doctrine-domain-events pull request #8
Opened 2022-07-01 17:27 UTC by mcsky

2022-07-02 22:11 UTC, Nek- requested changes
Thank you very much @mcsky . I really think this is the thing missing for a good developer experience with the bundle. 🙏 

Nevertheless, I have some feedbacks to fix before going for a merge.

2022-07-02 22:11 UTC, Nek- commented on Tests/PostFlushListener/EntitiesHasDispatcherCheckerTest.php
> +        // Use the Biig\Component\Domain\Model\Instantiator\Instantiator service for your own good.
```suggestion
        // Use the Biig\Component\Domain\Model\Instantiator\Instantiator service to instanciate your entities.
```

2022-07-02 22:11 UTC, Nek- commented on Tests/PostFlushListener/EntitiesHasDispatcherCheckerTest.php
> +        // Use the Biig\Component\Domain\Model\Instantiator\Instantiator service for your own good.
```suggestion
        // Use the Biig\Component\Domain\Model\Instantiator\Instantiator service to instanciate your entities.
```

2022-07-02 22:11 UTC, Nek- commented on Tests/PostFlushListener/EntitiesHasDispatcherCheckerTest.php
> +        $model = new FakeModel();
The model is not instantiated correctly here but still, the test passes? What is this dark magic?

2022-07-02 22:11 UTC, Nek- commented on Tests/config/config.yaml
> +parameters:
I think this file could be called `symfony_test_kernel_config.yaml` or something like this.

2022-07-02 22:11 UTC, Nek- commented on config/bundles.php
> +//    FriendsOfBehat\SymfonyExtension\Bundle\FriendsOfBehatSymfonyExtensionBundle::class => ['test' => true],
To be removed

2022-07-02 22:11 UTC, Nek- commented on config/bundles.php
> +    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
Not sure this is required here and it probably slows the test suite.

2022-07-02 22:11 UTC, Nek- commented on config/bundles.php
> +    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
Probably useless as well.

2022-07-02 22:11 UTC, Nek- commented on config/bundles.php
> +    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
Hum, this looks definitely useless here.

2022-07-02 22:11 UTC, Nek- commented on src/Exception/FlushedEntityDoesntContainsDispatcher.php
> +class FlushedEntityDoesntContainsDispatcher extends \Exception
```suggestion
class FlushedEntityDoesntContainsDispatcherException extends \LogicException
```

2022-07-02 22:11 UTC, Nek- commented on src/Exception/FlushedEntityDoesntContainsDispatcher.php
> +            ' See https://github.com/swagindustries/doctrine-domain-events#drawbacks , it exlain how to to it.',
Adding some doc about this exception in the drawbacks section would be nice.

2022-07-02 22:11 UTC, Nek- commented on Tests/PostFlushListener/EntitiesHasDispatcherCheckerTest.php
> +class EntitiesHasDispatcherCheckerTest extends KernelTestCase
Not gonna lie, I like the idea of testing it in a real world kernel. But I think it would be nice as well to add a unit test for it.

2022-07-04 15:27 UTC, mcsky commented on Tests/PostFlushListener/EntitiesHasDispatcherCheckerTest.php
> +        $model = new FakeModel();
the kernel isn't in debug mode

2022-07-05 13:09 UTC, mcsky commented on Tests/PostFlushListener/EntitiesHasDispatcherCheckerTest.php
> +class EntitiesHasDispatcherCheckerTest extends KernelTestCase
done ;)

2022-07-11 14:21 UTC, Nek- approved these changes

2022-07-11 14:21 UTC, Nek- commented on CHANGELOG.md
> +## [2.3.0] - 2022-07-08
We do not have a date for a release of the 2.3 version yet ! It will probably come with some more adjustments.

2022-07-11 14:22 UTC, Nek- commented on CHANGELOG.md
> +- Refactor the FakeModel test entity to use classic doctrine annotations.
Spaces after and before lists are missing

2022-07-11 16:23 UTC, merged